AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Story Transformer API

Globals:
  Function:
    Timeout: 60
    MemorySize: 256
    Runtime: python3.12

Parameters:
  Stage:
    Type: String
    Default: prod

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type'"
        AllowOrigin: "'*'"

  # Lambda 関数
  TransformerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handler.lambda_handler
      CodeUri: .
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: bedrock:InvokeModel
              Resource: '*'
      Events:
        Themes:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /themes
            Method: GET
        Transform:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /transform
            Method: POST
        Health:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /health
            Method: GET
        Options:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /{proxy+}
            Method: OPTIONS

Outputs:
  ApiUrl:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Stage}